//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXFromDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommitteesEntities : DbContext
    {
        public CommitteesEntities()
            : base("name=CommitteesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WS_ATTENDEES> WS_ATTENDEES { get; set; }
        public virtual DbSet<WS_COMMITTEE_CATEGORIES> WS_COMMITTEE_CATEGORIES { get; set; }
        public virtual DbSet<WS_COMMITTEE_PERMISSIONS> WS_COMMITTEE_PERMISSIONS { get; set; }
        public virtual DbSet<WS_COMMITTEES> WS_COMMITTEES { get; set; }
        public virtual DbSet<WS_HR_ITEMS> WS_HR_ITEMS { get; set; }
        public virtual DbSet<WS_ITEM_CATEGORIES> WS_ITEM_CATEGORIES { get; set; }
        public virtual DbSet<WS_ITEM_FILES> WS_ITEM_FILES { get; set; }
        public virtual DbSet<WS_MEETING_ITEMS> WS_MEETING_ITEMS { get; set; }
        public virtual DbSet<WS_MEETING_LOG> WS_MEETING_LOG { get; set; }
        public virtual DbSet<WS_MEETINGS> WS_MEETINGS { get; set; }
        public virtual DbSet<WS_OTHER_ITEMS> WS_OTHER_ITEMS { get; set; }
        public virtual DbSet<WS_ROLES> WS_ROLES { get; set; }
        public virtual DbSet<WS_STATUSES> WS_STATUSES { get; set; }
        public virtual DbSet<WS_USERS> WS_USERS { get; set; }
        public virtual DbSet<DB_SETTINGS> DB_SETTINGS { get; set; }
        public virtual DbSet<DEPARTMENTS_VW> DEPARTMENTS_VW { get; set; }
        public virtual DbSet<DIVISON_VW> DIVISON_VW { get; set; }
    }
}
