//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIVISON_VW
    {
        public string ORG_PARENT_CODE { get; set; }
        public string ORG_PARENT_NAME_ENG { get; set; }
        public string ORG_PARENT_NAME_ARA { get; set; }
    }
}
