//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WS_ATTENDEES
    {
        public string ATTENDEE_CODE { get; set; }
        public string ATTENDED { get; set; }
        public string APPROVE { get; set; }
        public string MEETING_CODE { get; set; }
        public string COMMITTEE_PERMISSION_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual WS_COMMITTEE_PERMISSIONS WS_COMMITTEE_PERMISSIONS { get; set; }
        public virtual WS_MEETINGS WS_MEETINGS { get; set; }
    }
}
