//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WS_COMMITTEES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WS_COMMITTEES()
        {
            this.WS_COMMITTEE_CATEGORIES = new HashSet<WS_COMMITTEE_CATEGORIES>();
            this.WS_COMMITTEE_PERMISSIONS = new HashSet<WS_COMMITTEE_PERMISSIONS>();
            this.WS_MEETINGS = new HashSet<WS_MEETINGS>();
        }
    
        public string COMMITTEE_CODE { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public string ADMIN { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string REMARKS { get; set; }
        public string LANGUAGE { get; set; }
        public string TITLE_ARABIC { get; set; }
        public string DESCRIPTION_ARABIC { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> MEETING_NUMBER_START { get; set; }
        public string FINAL_APPROVAL_REQUIRED { get; set; }
        public string REVIEW_REQUIRED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WS_COMMITTEE_CATEGORIES> WS_COMMITTEE_CATEGORIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WS_COMMITTEE_PERMISSIONS> WS_COMMITTEE_PERMISSIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WS_MEETINGS> WS_MEETINGS { get; set; }
    }
}
