//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WS_COMMITTEE_PERMISSIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WS_COMMITTEE_PERMISSIONS()
        {
            this.WS_ATTENDEES = new HashSet<WS_ATTENDEES>();
            this.WS_MEETINGS = new HashSet<WS_MEETINGS>();
            this.WS_MEETINGS1 = new HashSet<WS_MEETINGS>();
        }
    
        public string PERMISSIONS_CODE { get; set; }
        public string USERNAME { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> DISPLAY_ORDER { get; set; }
        public string ROLE_CODE { get; set; }
        public string COMMITTEE_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public string MODIFIED_DATE { get; set; }
        public string REMARKS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WS_ATTENDEES> WS_ATTENDEES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WS_MEETINGS> WS_MEETINGS { get; set; }
        public virtual WS_ROLES WS_ROLES { get; set; }
        public virtual WS_COMMITTEES WS_COMMITTEES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WS_MEETINGS> WS_MEETINGS1 { get; set; }
    }
}
