//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WS_MEETING_ITEMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WS_MEETING_ITEMS()
        {
            this.WS_HR_ITEMS = new HashSet<WS_HR_ITEMS>();
            this.WS_ITEM_FILES = new HashSet<WS_ITEM_FILES>();
            this.WS_OTHER_ITEMS = new HashSet<WS_OTHER_ITEMS>();
        }
    
        public string MEETING_ITEM_CODE { get; set; }
        public string COMMITTEE_APPROVAL { get; set; }
        public string COMMITTEE_RECOMMENDATION { get; set; }
        public string REVIEWER_REMARKS { get; set; }
        public string FINAL_APPROVAL { get; set; }
        public string STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string CATEGORY_CODE { get; set; }
        public string MEETING_CODE { get; set; }
        public string REMARKS { get; set; }
        public string REQUEST { get; set; }
        public string EXECUTE_BY { get; set; }
    
        public virtual WS_COMMITTEE_CATEGORIES WS_COMMITTEE_CATEGORIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WS_HR_ITEMS> WS_HR_ITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WS_ITEM_FILES> WS_ITEM_FILES { get; set; }
        public virtual WS_MEETINGS WS_MEETINGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WS_OTHER_ITEMS> WS_OTHER_ITEMS { get; set; }
    }
}
