//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WS_MEETINGS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WS_MEETINGS()
        {
            this.WS_ATTENDEES = new HashSet<WS_ATTENDEES>();
            this.WS_MEETING_ITEMS = new HashSet<WS_MEETING_ITEMS>();
            this.WS_MEETING_LOG = new HashSet<WS_MEETING_LOG>();
        }
    
        public string MEETING_CODE { get; set; }
        public decimal MEETING_NUMBER { get; set; }
        public Nullable<decimal> MEETING_YEAR { get; set; }
        public string STATUS { get; set; }
        public System.DateTime MEETING_DATE_TIME { get; set; }
        public string LOCATION { get; set; }
        public string COMMITTEE_APPROVAL { get; set; }
        public string FINAL_APPROVAL { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string COMMITTEE_CODE { get; set; }
        public string REMARKS { get; set; }
        public string START_TIME { get; set; }
        public string END_TIME { get; set; }
        public string FINAL_APPROVER_CODE { get; set; }
        public string REVIEWER_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WS_ATTENDEES> WS_ATTENDEES { get; set; }
        public virtual WS_COMMITTEE_PERMISSIONS WS_COMMITTEE_PERMISSIONS { get; set; }
        public virtual WS_COMMITTEE_PERMISSIONS WS_COMMITTEE_PERMISSIONS1 { get; set; }
        public virtual WS_COMMITTEES WS_COMMITTEES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WS_MEETING_ITEMS> WS_MEETING_ITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WS_MEETING_LOG> WS_MEETING_LOG { get; set; }
    }
}
