//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WS_ROLES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WS_ROLES()
        {
            this.WS_COMMITTEE_PERMISSIONS = new HashSet<WS_COMMITTEE_PERMISSIONS>();
        }
    
        public string ROLE_CODE { get; set; }
        public string TITLE { get; set; }
        public string TITLE_ARABIC { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string REMARKS { get; set; }
        public string DESCRIPTION_ARABIC { get; set; }
        public string DESCRIPTION { get; set; }
        public string ABBREVIATION { get; set; }
        public string ATTEND_MEETING { get; set; }
        public string DISPLAY_ORDER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WS_COMMITTEE_PERMISSIONS> WS_COMMITTEE_PERMISSIONS { get; set; }
    }
}
