//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WS_USERS
    {
        public string USERNAME { get; set; }
        public string NAME { get; set; }
        public string NAME_ARABIC { get; set; }
        public string BANNER_ID { get; set; }
        public string STATUS { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_TITLE_ENG { get; set; }
        public string ORG_TITLE_ARA { get; set; }
        public string POSN_NO { get; set; }
        public string POSN_TITLE_ENG { get; set; }
        public string POSN_TITLE_ARA { get; set; }
        public string GRADE { get; set; }
    }
}
